# Generated by Django 6.0.3 on 2026-03-07 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('dosagem', models.CharField(max_length=100)),
                ('unidade_estoque', models.CharField(choices=[('comprimidos', 'Comprimidos'), ('capsulas', 'Cápsulas'), ('ml', 'ml'), ('gotas', 'Gotas'), ('outro', 'Outro')], default='comprimidos', max_length=20)),
                ('quantidade_estoque', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('alerta_estoque_minimo', models.PositiveIntegerField(default=5)),
                ('frequencia_diaria', models.PositiveIntegerField(default=1)),
                ('horarios', models.JSONField(default=list)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
