# Generated by Django 6.0.3 on 2026-03-07 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_tomada', models.DateTimeField()),
                ('horario_previsto', models.CharField(blank=True, max_length=5)),
                ('quantidade_tomada', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('no_horario', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='medicamentos.medicamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_hora_tomada'],
            },
        ),
    ]
